// Generated by LiveScript 1.2.0
var express, x$;
express = require('express');
x$ = express();
x$.use('/tdiff', express['static'](__dirname + '/'));
x$.use('/file', express['static']('/'));
x$.listen(7416);
console.log('listening on 7416');